* Mike's Emacs Configuration
This repository contains my personal Emacs configuration. The setup includes optimized settings for different programming languages, especially Go, and various tools to improve productivity.

** Installation
To install the configuration, clone this repository into your home directory as follows:

#+begin_src sh
cd ~
git clone git@github.com:mikefaille/.emacs.d.git --recursive
#+end_src

The =--recursive= flag ensures that all submodules are also cloned.

** Setting Up Go
To setup Go in Emacs:

1. Install Go. Ensure that your =GOPATH= is set to =~/go=.
2. In Emacs, run the following command:

#+begin_src lisp
M-x go-projectile-install-tools
#+end_src

This will install the necessary Go tools.

** Platinum Searcher
To use the Platinum Searcher within this configuration, you need to install it first:

#+begin_src sh
go get -u github.com/monochromegane/the_platinum_searcher/...
#+end_src

** Optional Setup for Org-mode
For LaTeX support in Org-mode, you need to install =latexmk=.

** Python Setup
For Python development, the =jedi= package is used. To install the jedi server, run the following command in Emacs:

#+begin_src lisp
M-x jedi:install-server
#+end_src

This configuration provides a robust foundation for Python development, including autocompletion, syntax checking, and more.

Enjoy using this Emacs configuration, and feel free to customize it to your liking!
